defaults:
  - _self_
  - experiment: default
  - augmentation: default
  - model: efficientnetv2_s
  - criterion: ce
  - optimizers: adamw

DEBUG : true

INPUT_ROOT: data
OUTPUT_ROOT: output
MODEL_ROOT: model

SEED: 42

n_splits: 4
image_size: 224
n_classes: 2

EPOCHS: 10
batch_size: 16
warmup_steps: 0

device: cpu
# device: mps